### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [sorenvonsarvort/kotterstep-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a LICENSE - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by sorenvonsarvort** [comment]
Thank You for the interest. I appreciate it and would really like if the theme appears in the `awesome-zsh-plugins` list.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/682
